### ISSUE TITLE
Two page spreads

### ISSUE THREAD

**Issue by daniebker** [Laidout/laidout#12]
I'm trying to spread an image across two pages but the pdf doesn't seem to generate as I would expect it to when I export. Is it possible to spread an image across two pages? 

EDIT: I've checked through the youtube videos and don't see anything that's spreading across two pages. Also tried searching through the site but there doesn't seem to be anything.

**Comment by tomlechner** [comment]
Except for centerfolds, bleeding objects across page boundaries doesn't work. I have a plan to fix that, just haven't yet, I need to implement proper object masking first.

If the object is on a centerfold, it should be ok, as long as it doesn't fall in a trim gutter.

As a workaround, you can set the page to clip at boundaries, by pressing the Page Clip button next to the color box on the bottom of the window for both pages, add the same object to each page (with space bar duplicate while holding with mouse with object tool), and position manually. Not a pleasant workaround, but should at least work!

**Comment by tomlechner** [comment]
....Err, unless page clip broke somehow! I'm trying on current git, and the object blanks out when I try to do that. Will investigate.

**Comment by daniebker** [comment]
I tried the page clip without cloning the image, the image disappeared (the object frame remained, Is this the same issue you're seeing with page clipping?). The export worked as expected with the image clipped on the right page. I then tried cloning the image across the two pages and turning on page clipping. However now the problem is I can't export: `Warning: id:Clone22020, Cannot export SomeDataRef objects to pdf.` I'm building and installing master on Debian 9.6.

I'll keep trying to see if it's something I'm doing anything wrong. Let me know if you need anything else.

Also, thanks for making this :) I'll try and help in any way that I can.

**Comment by tomlechner** [comment]
Yes, the image disappearing is the same issue I see, something to do with cairo and clip masks I think. Sometimes the image pops in and out when zooming for unknown reasons. Working on it. 

Getting clones to output to pdf should be easier to fix. A workaround is to use duplicates instead of clones. With the mouse button held on an object, pressing plain space should duplicate the object, while control-space clones.

Bug reports, feature requests, and patches always welcome! I have a long todo list, and I don't always prioritize very rationally, but I do try to fix stuff people tell me about.

**Comment by tomlechner** [comment]
In current git, pdf should export clones now, but only tested against image clones. In viewing the exported pdf, let me know if there's any strange errors, my fix takes a shortcut that "shouldn't" matter, but one never knows for sure.

Not sure about the render bug yet.

**Comment by tomlechner** [comment]
Huh. One line fix for the blanking out things in the window when pages clip. Easier than I expected. Now fixed in current git.

**Comment by daniebker** [comment]
Great! I was just able to export, thanks! Just a couple more questions, is there a way to clone to the next page or do I have to move the image t the other page and then realign it? I think I remember seeing a tool to help with alignment but I can't bring it back up, is there a shortcut for page alignments?

Thanks again..

**Comment by tomlechner** [comment]
If you are in the "Pages" view (as opposed to "Single" or "Papers" view), to move to another visible page, just drag the object so that it is entirely within the other page. Alternately, to move to any page including ones not visible, drag out into "Limbo", the area totally out of any page, then switch to another page, and drag into that page.

To align, select all the objects you want to align, right click and select align (or just press 'a'). If you just want to put the objects at the same place visually, hold control, press and move the left mouse button, select the center thing in the box that comes up. Done! Escape to leave alignment tool. In retrospect I should probably map control-left-mouse-press-and-move to something less obtuse.

Here's everything with the alignment tool: http://laidout.org/screenshots/img-align.html

**Comment by tomlechner** [comment]
Also, if you hit 'i', it will toggle the Object Indicator so you can tell at a glance which page actually owns the selected object. And pressing 'tab' will cycle through objects in your view.

**Comment by tomlechner** [comment]
Just implemented object clipping paths and object bleeding across pages based on the Page View so you don't have to hack it with duplicates. This system currently exports to Svg, Pdf, and Image. At some point it will work for Scribus export, but that's on hold as I need to do a more comprehensive overhaul of the scribus export to cope with Scribus file format changes from the last couple of years!

Feel free to open this issue again if there's other problems with this, or start a new issue.
