### ISSUE TITLE
SIGABRT when opening laidout document

### ISSUE THREAD

**Issue by madsl** [Laidout/laidout#24]
Great software, just used it to create a booklet, worked wonderfully!

But one thing - what extensions are laidout files supposed to have? I just used ".laidout" on the layout I just created, but when I try to open it again I get a SIGABRT:

Here's the console output when clicking on the file in Laidout:
```
TextEditBaseUtf8:: NewText
A new book.laidout
foundcaret: 2,16.5
refcounted anobject dec count, now: 0, deleting
anObject 4097 dec counted: 0  (?)
refcounted anobject dec count, now: 22
ImageLoader 104 dec counted: 22  (?)
anObject tracker 4097   destroyed (?) num of anObjects: 2370
ImageLoader::LoadImage()...A new book.laidout
GraphicsMagick Error loading A new book.laidout
ImageLoader::LoadImage() couldn't load A new book.laidout
ImageLoader::LoadImage().../home/mads/Documents/Sara/A new book.laidout
GraphicsMagick Error loading /home/mads/Documents/Sara/A new book.laidout
ImageLoader::LoadImage() couldn't load /home/mads/Documents/Sara/A new book.laidout
double free or corruption (out)
Magick: abort due to signal 6 (SIGABRT) "Abort"...
Aborted (core dumped)
```

Does this have anything to do with that Laidout tries to open the laidout file as an image in GraphicsMagick? What extension should I use for this to not happen? The best would be that saving a layout file would automatically add the correct extension when it's missing, I guess...

**Comment by madsl** [comment]
Hm weird, I updated that Gentoo ebuild to run laxkit configure with --disable-gl and `make touchdepends hidegarbage` in the laxkit dir before building, and now the bug doesn't trigger anymore...

Does laidout documents have a file extension though? :p

**Comment by tomlechner** [comment]
Was it failing when you hit open, or when you just click on the file in the file dialog? Possibly it's trying to preview the file, and chaos ensues for some reason. 

It should never crash though! Very much a bug if it crashes when GraphicsMagick is trying to open a .laidout file, which is what it looks like.. Even then, that shouldn't be crash inducing. If you can reproduce it, a log (made from a build without the hidegarbage part) might help narrow it down.

Theoretically, the extension shouldn't matter at all (I usually use ".laidout"). Laidout is supposed to examine the first 100 bytes or so of files to figure out how to open something. When opening random files (from the Open tab when you start Laidout, or from the command line) it's supposed to check if it's a Laidout file, an SVG, or a Scribus file, otherwise currently opening fails and it should show a popup saying it couldn't open it... Though I notice it fails silently when I control-o while running Laidout!

**Comment by madsl** [comment]
It was during the preview, yes, right after clicking on the file.

**Comment by tomlechner** [comment]
I can't reproduce this so far. I guess something is either corrupted or something that was freed is trying to be accessed, but I don't see anything obvious in the previewer code.

**Comment by madsl** [comment]
Can't reproduce it myself either, I think I'll just close this one for now...
